version: "3.9"
services:

  web-spring-boot-artifact:
    build: .
    #image: remayke/spring-web:1.0 # Usado caso jรก exista a imagem
    #image: spring/dock
    container_name: appweb
    volumes:
      - meu-volume:/app
    ports:
      - 3000:8080
    networks:
      - minha-rede
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4.6
    container_name: meu-mongo
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge

volumes:
  meu-volume:
    # Pode deixar vazio se deseja criar um novo volume 
    # external: true # true=Usado se o volume ja existir
