name: Spring-Docker CI/CD

env:
  IMAGE_NAME: remayke/learning
  IMAGE_TAG: github
  DOCKER_USERNAME: remayke

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]


jobs:
  

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: remove ssh command using pass
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASS }}
        script: export PATH=$PATH:/usr/bin/docker &&
                echo ${{secrets.DOCKER_PASS}} | docker login --username "${{env.DOCKER_USERNAME}}" --password-stdin &&
                docker ps -aq | xargs --no-run-if-empty docker stop &&
                docker ps -aq | xargs --no-run-if-empty docker rm &&
                docker images -aq | xargs --no-run-if-empty docker rmi &&
                docker run -d -p 80:8080 ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
