name: Java CI with Maven

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  
  test:
    runs-on: ubuntu-latest
    # runs-on: ${{matrix.os}}
    # strategy:
      # matrix:
        # os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Instalando JDK17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    - name: Testando a aplicacao
      run: ./mvnw clean test
        


  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    - name: Empacotando a aplicacao
      run: ./mvn clean package
    - name: Build docker container
      run: docker-compose build