name: Spring-Docker CI/CD

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]


jobs:
  

  test-build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
        
    - run: ./mvnw clean package

    - uses: actions/upload-artifact@master
      with:
        name: app.jar
        path: ./target/*.jar
        


  docker:
    needs: test-build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - uses: actions/download-artifact@master
      with:
        name: app.jar
        path: ./target/app.jar
        
    - run: docker-compose build
    
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: remayke
        password: ${{ secrets.DOCKERHUB_PASS }}
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: remayke/learning:ultima
