name: Spring-Docker CI/CD

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]


jobs:
          
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: remove ssh command using pass
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASS }}
        script: |
                docker stop $(docker ps -aq) &>/dev/null || true \
                docker rm $(docker ps -aq) &>/dev/null || true \
                docker rmi $(docker images -aq) &>/dev/null || true \
                docker run -d -p 80:8080 remayke/learning:ultima
