name: Spring-Docker CI/CD

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]


jobs:
  

  test:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
        
    -  run: ./mvnw clean package

    - uses: actions/upload-artifact@master
      with:
        name: app.jar
        path: ./target/*.jar
        


  build:
    needs: test
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - uses: actions/download-artifact@master
      with:
        name: app.jar
        path: ./target/app.jar
        
    -  run: docker-compose build